"""updated table field names to common name to reduce enums

Revision ID: a6a53b72bcd6
Revises: 
Create Date: 2025-10-11 18:48:00.448513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Float, Integer
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a6a53b72bcd6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted to rename columns instead of removing and adding new ones ###
    op.alter_column('cultural_value', 'heritage_score',
                    new_column_name='cultural_score',
                    type_=Float)
    op.alter_column('user_country_score', 'budget_score',
                    new_column_name='cost_score',
                    type_=Float)
    op.alter_column('user_country_score', 'culture_score',
                    new_column_name='cultural_score',
                    type_=Float)
    op.alter_column('user_travel_score', 'budget_user_score',
                    new_column_name='cost_score',
                    type_=Integer)
    op.alter_column('user_travel_score', 'water_sports_user_score',
                    new_column_name='water_sports_score',
                    type_=Integer)
    op.alter_column('user_travel_score', 'winter_sports_user_score',
                    new_column_name='winter_sports_score',
                    type_=Integer)
    op.alter_column('user_travel_score', 'nature_user_score',
                    new_column_name='nature_score',
                    type_=Integer)
    op.alter_column('user_travel_score', 'safety_user_score',
                    new_column_name='safety_score',
                    type_=Integer)
    op.alter_column('user_travel_score', 'culture_user_score',
                    new_column_name='cultural_score',
                    type_=Integer)
    op.alter_column('user_travel_score', 'pop_density_user_score',
                    new_column_name='pop_density_score',
                    type_=Integer)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cultural_value', 'cultural_score',
                    new_column_name='heritage_score',
                    type_=Float)
    op.alter_column('user_country_score', 'cost_score',
                    new_column_name='budget_score',
                    type_=Float)
    op.alter_column('user_country_score', 'cultural_score',
                    new_column_name='culture_score',
                    type_=Float)
    op.alter_column('user_travel_score', 'cost_score',
                    new_column_name='budget_user_score',
                    type_=Integer)
    op.alter_column('user_travel_score', 'water_sports_score',
                    new_column_name='water_sports_user_score',
                    type_=Integer)
    op.alter_column('user_travel_score', 'winter_sports_score',
                    new_column_name='winter_sports_user_score',
                    type_=Integer)
    op.alter_column('user_travel_score', 'nature_score',
                    new_column_name='nature_user_score',
                    type_=Integer)
    op.alter_column('user_travel_score', 'safety_score',
                    new_column_name='safety_user_score',
                    type_=Integer)
    op.alter_column('user_travel_score', 'cultural_score',
                    new_column_name='culture_user_score',
                    type_=Integer)
    op.alter_column('user_travel_score', 'pop_density_score',
                    new_column_name='pop_density_user_score',
                    type_=Integer)
    # ### end Alembic commands ###
